spring.application.name=agrosat

# Oracle
spring.datasource.url=jdbc:oracle:thin:@oracle.fiap.com.br:1521:orcl
spring.datasource.driver-class-name=oracle.jdbc.OracleDriver
spring.datasource.username=SEU_RM
spring.datasource.password=SUA_SENHA
spring.jpa.database-platform=org.hibernate.dialect.OracleDialect
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=false

# Cache
spring.cache.type=simple

# NASA POWER API
nasa.power.api.url=https://power.larc.nasa.gov/api/temporal/daily/point
openmeteo.api.url=https://api.open-meteo.com/v1/forecast
